"""convert.py — CML YAML → Network Sketcher command converter (local-file edition).

Reads a CML Lab topology YAML exported from the CML UI (or generated by the
CML API) and optionally a directory of running-config text files, then emits
a ready-to-use Network Sketcher command script.

Usage::

    python cml_converter/src/convert.py \\
        --yaml  <cml_topology.yaml>         \\
        [--configs <running_configs_dir/>]   \\
        [--out   ns_commands.txt]

Outputs (written to the same directory as ``--out`` unless ``--out`` is an
absolute path):

- ``ns_commands.txt``       – NS ``run_commands`` input (Phase 1-6)
- ``ns_model.json``         – intermediate topology model (debug)
- ``stencil_mapping.csv``   – stencil type mapping table (audit)
- ``parse_report.md``       – per-device config coverage statistics

The tool deliberately has **no** dependency on the CML REST API.  All input
comes from local files only.
"""
from __future__ import annotations

import argparse
import csv
import json
import pathlib
import sys
from typing import Any, Dict, Optional

import yaml


# ---------------------------------------------------------------------------
# Relative imports (all siblings live in this package)
# ---------------------------------------------------------------------------
from .stencil_mapper import map_all, to_csv_rows
from .config_parser import parse_all
from .topology_mapper import build_ns_model, model_to_dict
from .ns_command_builder import build_command_script


# ---------------------------------------------------------------------------
# YAML loader helpers
# ---------------------------------------------------------------------------

def _load_yaml(path: pathlib.Path) -> Any:
    with path.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def _extract_topology(data: Any) -> tuple[list, list]:
    """Return (nodes, links) from a CML YAML structure.

    CML Lab YAMLs have two common top-level shapes:

    1. Direct export (``cml-extras`` / ``lab`` key)::

         lab:
           nodes: [...]
           links: [...]

    2. Flat API dump (``nodes`` / ``links`` at root level).
    """
    if isinstance(data, dict):
        if "lab" in data:
            lab = data["lab"]
            return lab.get("nodes") or [], lab.get("links") or []
        # Try common API format where topology is nested.
        if "topology" in data:
            topo = data["topology"]
            return topo.get("nodes") or [], topo.get("links") or []
        # Flat format.
        nodes = data.get("nodes") or []
        links = data.get("links") or []
        return nodes, links
    raise ValueError(
        f"Unexpected YAML root type: {type(data).__name__}. "
        "Expected a mapping with 'lab', 'topology', or 'nodes'/'links' keys."
    )


# ---------------------------------------------------------------------------
# Running-config loader
# ---------------------------------------------------------------------------

def _load_running_configs(configs_dir: Optional[pathlib.Path]) -> Dict[str, str]:
    """Load ``*.txt`` / ``*.cfg`` / ``*.conf`` files from a directory.

    File stems are used as the device label key so that they must match the
    CML node ``label`` fields exactly.  Example: a file ``spine1.txt``
    matches a node with ``label: spine1``.
    """
    if not configs_dir:
        return {}
    if not configs_dir.is_dir():
        print(f"[WARN] --configs path is not a directory: {configs_dir}", file=sys.stderr)
        return {}
    configs: Dict[str, str] = {}
    for p in sorted(configs_dir.iterdir()):
        if p.suffix.lower() in {".txt", ".cfg", ".conf"}:
            try:
                configs[p.stem] = p.read_text(encoding="utf-8", errors="replace")
            except OSError as exc:
                print(f"[WARN] Cannot read config file {p}: {exc}", file=sys.stderr)
    return configs


# ---------------------------------------------------------------------------
# Report builders
# ---------------------------------------------------------------------------

def _write_parse_report(
    out_dir: pathlib.Path,
    stats: Dict[str, Dict[str, int]],
    nodes: list,
    parsed_configs: Dict[str, Any],
) -> None:
    node_labels = {str(n.get("label", "")) for n in nodes}
    covered = set(parsed_configs.keys()) & node_labels
    report_path = out_dir / "parse_report.md"
    lines = [
        "# CML → NS Conversion — Parse Report\n",
        f"**Topology devices**: {len(node_labels)}  ",
        f"**Configs provided**: {len(parsed_configs)}  ",
        f"**Coverage**: {len(covered)}/{len(node_labels)} "
        f"({100 * len(covered) // max(len(node_labels), 1)}%)\n",
        "## Per-device statistics\n",
        "| Device | VLANs | SVIs | Loopbacks | L3 phys | L2 trunks | L2 access | PortChs | VRFs |",
        "|--------|-------|------|-----------|---------|-----------|-----------|---------|------|",
    ]
    for label in sorted(node_labels):
        st = stats.get(label, {})
        lines.append(
            f"| {label} "
            f"| {st.get('vlans', '-')} "
            f"| {st.get('svi', '-')} "
            f"| {st.get('loopback', '-')} "
            f"| {st.get('l3_phys', '-')} "
            f"| {st.get('l2_trunk', '-')} "
            f"| {st.get('l2_access', '-')} "
            f"| {st.get('portchannel', '-')} "
            f"| {st.get('vrf', '-')} |"
        )
    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  parse_report.md  → {report_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert a CML YAML topology file into Network Sketcher commands.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--yaml", "-y",
        required=True,
        metavar="CML_TOPOLOGY.yaml",
        help="Path to CML Lab YAML (UI export or API dump).",
    )
    parser.add_argument(
        "--configs", "-c",
        default=None,
        metavar="CONFIGS_DIR",
        help="Directory containing running-config files (*.txt / *.cfg). "
             "File stems must match CML node labels. Optional.",
    )
    parser.add_argument(
        "--out", "-o",
        default="ns_commands.txt",
        metavar="OUTPUT_FILE",
        help="Destination for the NS command script. "
             "Side-outputs (ns_model.json etc.) are written to the same directory. "
             "Default: ns_commands.txt",
    )
    args = parser.parse_args(argv)

    yaml_path = pathlib.Path(args.yaml).resolve()
    configs_dir = pathlib.Path(args.configs).resolve() if args.configs else None
    out_path = pathlib.Path(args.out).resolve()
    out_dir = out_path.parent
    out_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Step 1: load YAML
    # ------------------------------------------------------------------
    print(f"[1/6] Loading CML YAML: {yaml_path}")
    try:
        raw_data = _load_yaml(yaml_path)
    except FileNotFoundError:
        print(f"[ERROR] File not found: {yaml_path}", file=sys.stderr)
        return 1
    except yaml.YAMLError as exc:
        print(f"[ERROR] YAML parse error: {exc}", file=sys.stderr)
        return 1

    nodes, links = _extract_topology(raw_data)
    print(f"         nodes={len(nodes)}, links={len(links)}")

    # ------------------------------------------------------------------
    # Step 2: stencil mapping
    # ------------------------------------------------------------------
    print("[2/6] Mapping stencils …")
    stencil_list = map_all(nodes)
    stencil_map = {s.label: s for s in stencil_list}

    csv_path = out_dir / "stencil_mapping.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerows(to_csv_rows(stencil_list))
    print(f"  stencil_mapping.csv → {csv_path}")

    low_conf = [s for s in stencil_list if s.confidence < 0.5]
    if low_conf:
        print(f"  [WARN] {len(low_conf)} device(s) have low-confidence stencil mapping "
              f"(confidence < 0.5). Review stencil_mapping.csv.")

    # ------------------------------------------------------------------
    # Step 3: running-config parsing
    # ------------------------------------------------------------------
    print("[3/6] Loading running configs …")
    raw_configs = _load_running_configs(configs_dir)
    parsed_configs = parse_all(raw_configs) if raw_configs else {}
    print(f"         parsed {len(parsed_configs)} config(s)")

    # ------------------------------------------------------------------
    # Step 4: build NS model
    # ------------------------------------------------------------------
    print("[4/6] Building NS topology model …")
    model, parse_stats = build_ns_model(nodes, links, stencil_map, parsed_configs)

    model_path = out_dir / "ns_model.json"
    model_path.write_text(
        json.dumps(model_to_dict(model), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"  ns_model.json    → {model_path}")

    # ------------------------------------------------------------------
    # Step 5: generate NS commands
    # ------------------------------------------------------------------
    print("[5/6] Generating NS commands …")
    script = build_command_script(model)
    out_path.write_text(script.text(), encoding="utf-8")
    print(f"  ns_commands.txt  → {out_path}")
    total_cmds = sum(script.counts.values())
    print(f"         {total_cmds} command(s) across {len(script.counts)} phase(s)")

    # ------------------------------------------------------------------
    # Step 6: parse report
    # ------------------------------------------------------------------
    print("[6/6] Writing parse report …")
    _write_parse_report(out_dir, parse_stats, nodes, parsed_configs)

    print("\n[Done] All outputs written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
